-- Generated from the approved UNDP Project Portfolio workbook. Do not edit generated values by hand.

BEGIN;

CREATE TEMP TABLE portfolio_import (
title text NOT NULL,
  slug text NOT NULL,
  match_slugs text[] NOT NULL DEFAULT ARRAY[]::text[],
  summary text NOT NULL,
  description text NOT NULL,
  project_status text NOT NULL,
  project_year integer,
  impact_area text NOT NULL,
  work_stream text NOT NULL,
  capabilities_involved text[] NOT NULL DEFAULT ARRAY[]::text[],
  best_fit text[] NOT NULL DEFAULT ARRAY[]::text[],
  problem text NOT NULL,
  solution text NOT NULL,
  how_it_works text[] NOT NULL DEFAULT ARRAY[]::text[],
  features text[] NOT NULL DEFAULT ARRAY[]::text[],
  tech_stack text[] NOT NULL DEFAULT ARRAY[]::text[],
  collaboration_network text NOT NULL,
  implementation_countries text[] NOT NULL DEFAULT ARRAY[]::text[],
  resource_links text[] NOT NULL DEFAULT ARRAY[]::text[],
  video_url text,
  display_order integer NOT NULL
) ON COMMIT DROP;

INSERT INTO portfolio_import (title, slug, match_slugs, summary, description, project_status, project_year, impact_area, work_stream, capabilities_involved, best_fit, problem, solution, how_it_works, features, tech_stack, collaboration_network, implementation_countries, resource_links, video_url, display_order) VALUES
('Land Use Analysis Tool', 'land-use-analysis-tool', ARRAY[]::text[], 'A GIS- and AI-powered tool that maps and monitors land-use and deforestation changes over time and simulates future land-use scenarios, helping governments make data-driven decisions for sustainable land management.', 'A GIS- and AI-powered tool that maps and monitors land-use and deforestation changes over time and simulates future land-use scenarios, helping governments make data-driven decisions for sustainable land management.', 'active', 2025, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'GIS', 'remote sensing / satellite imagery', 'predictive and scenario modeling', 'web-based data visualization']::text[], ARRAY['UNDP Country Offices, Governments (national ministries and agencies)']::text[], 'Land and forests face growing pressure from urbanization and climate change, but traditional land-use monitoring is often slow, fragmented, and lacks the precision and predictive power needed for timely, data-driven decisions.', 'SDG AI Lab built an open-source tool that combines satellite imagery, machine learning, and web-based GIS to map land-use and deforestation changes, predict high-risk areas, and simulate future land-use scenarios for sustainable planning.', ARRAY['Ingest multi-source satellite imagery (optical + radar) plus terrain, climate, and socio-economic data', 'Classify land cover and detect change with machine-learning models', 'Predict high-risk areas and future land-use trends', 'Simulate policy options through a three-stage simulation engine', 'Visualize results on an interactive web-GIS dashboard with automated reports']::text[], ARRAY['Land-cover mapping and multi-temporal change monitoring', 'Deforestation detection and alerts', 'Predictive modeling of land-use change and risk', 'Scenario builder for policy simulation', 'Interactive web-GIS dashboards and automated reporting', 'Open-source, customizable, and multilingual']::text[], ARRAY['Python', 'Google Earth Engine', 'Sentinel-1 (SAR)', 'Sentinel-2 (optical)', 'Landsat 8/9', 'MODIS imagery', 'SRTM DEM', 'NDVI/EVI indices', 'Random Forest', 'CNN (ResNet18)', 'ANN', 'Markov Chain and Cellular Automata models', 'Django REST Framework', 'PostgreSQL/PostGIS', 'Redis/Celery', 'GDAL', 'Docker', 'React.js', 'Leaflet/MapLibre', 'WMS and GeoJSON REST APIs']::text[], 'Collaborated with UNDP Country Offices (Guinea, Kazakhstan, Peru, Ecuador, Nepal, and Kyrgyzstan) and, in Kazakhstan, with National Information Technologies JSC (NIT); designed to align with national systems such as Guinea''s National Forest and Land Use Monitoring System (SNSF), with habitat-monitoring data input from the Connected Conservation Foundation.', ARRAY['Piloted in Kazakhstan (North Kazakhstan Region)', 'Basic implementations also run for Guinea, Kyrgyzstan, Ecuador']::text[], ARRAY[]::text[], NULL, 1),
('Audit Recommendation Tracking Tool (ARTT)', 'audit-recommendation-tracking-tool-artt', ARRAY[]::text[], 'ARTT is a web platform that helps national audit institutions track what happens after an audit report is published. It follows each recommendation from issuance to verified implementation and formal closure, so corrective actions are recorded, evidenced, and reported.', 'ARTT is a web platform that helps national audit institutions track what happens after an audit report is published. It follows each recommendation from issuance to verified implementation and formal closure, so corrective actions are recorded, evidenced, and reported.', 'completed', 2024, 'Natural Language Processing', 'NLP', ARRAY['AI/ML', 'NLP', 'Generative AI (LLM)', 'OCR and document extraction', 'Web development', 'Data visualisation']::text[], ARRAY['UNDP Multi-Country Offices, Governments (Supreme Audit Institutions and audited entities)']::text[], 'Audit institutions issue reports with findings and recommendations, but follow-up is handled manually through spreadsheets, letters, and email. There is no standard way to confirm whether corrective actions were implemented.', 'A remediation platform that ingests published audit reports, extracts recommendations with AI, assigns ownership to audited entities, and enforces an evidence-based workflow through verification and final closure.', ARRAY['Auditor uploads the audit report PDF', 'AI extracts metadata, findings, recommendations, and management responses', 'Auditor reviews and approves the extracted data', 'Audited entity responds, submits an action plan, and uploads evidence', 'Auditor verifies evidence; Head of SAI signs off final closure']::text[], ARRAY['AI-assisted extraction of audit findings and recommendations', 'Five-state recommendation lifecycle with enforced transitions', 'Management Action Plans with locked target dates and change requests', 'Evidence upload required before verification', 'Role-based dashboards, tracker, and filtering for seven user roles', 'AI-generated stakeholder reports for citizens, media, parliament, and audited entities']::text[], ARRAY['React 18 + TypeScript', 'Tailwind CSS', 'D3.js', 'Django 5.1 + Django REST Framework', 'Python 3.12', 'PostgreSQL 15', 'Redis 7', 'Django Q2', 'LangGraph with Azure OpenAI (GPT-4)', 'PyMuPDF4LLM', 'Tesseract OCR', 'Docker Compose']::text[], 'Designed, developed, and delivered by the SDG AI Lab in collaboration with the UNDP Pacific Multi-Country Office, under the Vaka Pasifika initiative supported by the European Union.', ARRAY['Cook Islands', 'Fiji', 'Federated States of Micronesia', 'Marshall Islands', 'Palau', 'Solomon Islands']::text[], ARRAY[]::text[], NULL, 2),
('Tensions Monitoring System (TMS) Portal Upgrade', 'tensions-monitoring-system-tms-portal-upgrade', ARRAY[]::text[], 'An upgrade of Lebanon''s Tensions Monitoring System that adds interactive maps, AI tools, and automated reporting to the existing platform, making data on social tensions and vulnerability easier to explore and act on.', 'An upgrade of Lebanon''s Tensions Monitoring System that adds interactive maps, AI tools, and automated reporting to the existing platform, making data on social tensions and vulnerability easier to explore and act on.', 'active', 2026, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'GIS', 'NLP', 'remote sensing / satellite imagery', 'web development', 'RAG']::text[], ARRAY['UNDP Country Offices']::text[], 'Lebanon''s existing Tensions Monitoring System offers valuable data but lacks a holistic view of social, economic, and environmental responses; its static, report-style outputs limit the fast, granular, scenario-based analysis needed for early, preventive action.', 'SDG AI Lab is upgrading the platform (TMS 2.0) by adding an interactive mapping tool, social-vulnerability indices, AI tools, a chatbot, and automated reporting, so users can explore layered data and run "what-if" scenarios in one portal.', ARRAY['Calculate social-vulnerability and other indices from survey and socio-economic data', 'Collect and integrate geospatial data into high-resolution heatmaps', 'Build an interactive mapping tool with layering, split-view, and "what-if" scenarios', 'Add AI tools, a chatbot, and automated report generation', 'Integrate into the existing TMS and hand over to UNDP Lebanon']::text[], ARRAY['Interactive, layered map visualizations', 'Split-mapping ("before/after") views', 'Scenario editing ("what-if") functions', 'High-resolution vulnerability heatmaps', 'Chatbot and automated report generation', 'Open-source, low-maintenance, integrated into the existing platform']::text[], ARRAY['HTML', 'JavaScript', 'Leaflet (interactive maps)', 'Principal Component Analysis and machine-learning regression', 'GIS and remote sensing (incl. nightlight data)', 'NLP and RAG (chatbot)', 'open datasets such as OpenStreetMap and the Humanitarian Data Exchange']::text[], 'Collaborated with the UNDP Lebanon Country Office. The broader Tensions Monitoring System is run jointly by UNDP and UNHCR in Lebanon, in collaboration with the Ministry of Social Affairs (MoSA) and the Ministry of Interior and Municipalities (MoIM).', ARRAY['Lebanon']::text[], ARRAY[]::text[], NULL, 3),
('INFF II (Financing Strategy Database Automation)', 'inff-ii-financing-strategy-database-automation', ARRAY[]::text[], 'A tool that automatically pulls data from countries'' national financing-strategy documents into a structured, searchable database with real-time dashboards, making it easier to track and compare how countries plan to finance their development goals.', 'A tool that automatically pulls data from countries'' national financing-strategy documents into a structured, searchable database with real-time dashboards, making it easier to track and compare how countries plan to finance their development goals.', 'active', 2025, 'Natural Language Processing', 'NLP', ARRAY['AI/ML', 'data engineering', 'document/PDF data extraction', 'taxonomy/ontology', 'data visualization (Power BI)', 'RAG']::text[], ARRAY['UNDP HQ (Sustainable Finance Hub / INFF Facility)']::text[], 'As Integrated National Financing Frameworks expand across many countries, key information sits in scattered, document-heavy reports that are hard to compare and track, making it difficult to manage financing-strategy data consistently or use it for evidence-based policy.', 'SDG AI Lab expanded the financing-strategy database and built an end-to-end pipeline that extracts data from PDF reports into structured datasets, feeding a centralized database and real-time Power BI dashboards for easier analysis and comparison across countries.', ARRAY['Collect national financing-strategy documents (e.g. PDF reports)', 'Extract and structure the data into standardized datasets', 'Tag entries against a shared taxonomy (categories, markers, regions)', 'Feed outputs into a centralized database', 'Visualize and compare in real-time Power BI dashboards']::text[], ARRAY['Automated extraction from PDF and other documents', 'Structured, standardized financing-strategy dataset', 'Shared taxonomy for consistent classification', 'Covers 30+ countries'' financing strategies', 'Real-time Power BI dashboards', 'Scalable to new data sources and AI analytics']::text[], ARRAY['Power BI', 'Excel (structured outputs and ontology)', 'automated PDF/document data extraction', 'RAG', 'AI/ML models', 'data pipelines and connectors']::text[], 'Collaborated with the INFF Facility and the UNDP Sustainable Finance Hub (SFH), building on earlier joint work; designed to also incorporate data from ministries and INFF partners.', ARRAY['Global (developed with the INFF Facility)', 'The database compiles national financing strategies from 30+ countries']::text[], ARRAY[]::text[], NULL, 4),
('Public Finance Simplification App', 'public-finance-simplification-app', ARRAY['public-finance-simplification-platform-pfs']::text[], 'An AI-powered platform that turns complex government budget and audit documents into clear, interactive dashboards and plain-language reports, helping citizens, civil society, and officials understand and monitor public finances.', 'An AI-powered platform that turns complex government budget and audit documents into clear, interactive dashboards and plain-language reports, helping citizens, civil society, and officials understand and monitor public finances.', 'completed', 2024, 'Natural Language Processing', 'NLP', ARRAY['AI/ML', 'GenAI and Large Language Models', 'NLP', 'data visualization', 'web and mobile development', 'RAG']::text[], ARRAY['UNDP Pacific Multi-Country Office, Government']::text[], 'Government budget and audit documents are large, technical, and buried in spreadsheets, making it hard to compare spending across years, sectors, and ministries — and leaving citizens, civil society, and media without accessible information to engage in fiscal oversight.', 'SDG AI Lab built an AI-powered platform that analyzes public finance documents, generates plain-language reports, and presents budget and expenditure data as interactive dashboards, with community features and multi-language support so citizens can explore and discuss national finances.', ARRAY['Upload public finance documents (budget, expenditure, audit)', 'AI/LLMs extract data and generate plain-language reports', 'Present budget vs. expenditure as interactive dashboards', 'Drill down by ministry, sector, and year; export to PDF/CSV', 'Engage via forum, comments, and chatbot, in local languages']::text[], ARRAY['Interactive budget & expenditure dashboards with ministry/sector/year drill-down', 'AI-generated narrative reports from structured data', 'Multi-year comparison and multi-country support', 'Export suite (PDF, CSV, charts)', 'Community forum, comments, and moderation tools', 'Multi-language support, chatbot, and mobile app']::text[], ARRAY['Power BI', 'machine learning', 'Large Language Models / GenAI', 'RAG', 'chatbot', 'cloud hosting', 'web and mobile app (OpenAI API and open-source LLM options evaluated)']::text[], 'Collaborated with the UNDP Pacific Multi-Country Office as part of its Vaka Pasifika project (supported by the European Union), engaging Fiji government stakeholders, civil society, and media.', ARRAY['Fiji']::text[], ARRAY[]::text[], NULL, 5),
('Madagascar Multihazard Early Warning System', 'madagascar-multihazard-early-warning-system', ARRAY[]::text[], 'The Madagascar Multihazard Early Warning Dashboard integrates multiple hazards—including drought, floods, cyclones, landslides, and epidemics—into a unified early warning platform combining real-time data, predictive analytics, and interactive mapping for improved preparedness and response.', 'The Madagascar Multihazard Early Warning Dashboard integrates multiple hazards—including drought, floods, cyclones, landslides, and epidemics—into a unified early warning platform combining real-time data, predictive analytics, and interactive mapping for improved preparedness and response.', 'active', 2025, 'GIS / Remote Sensing', 'GIS', ARRAY['Risk analytics', 'Data integration', 'Dashboards', 'AI', 'GIS']::text[], ARRAY['UNDP, UN Entities, Government']::text[], 'Madagascar lacks a harmonized system to manage multiple, cascading hazards like droughts, cyclones, and floods. This fragmentation leads to inefficient, reactive responses, worsening socioeconomic impacts on vulnerable populations.', 'A unified digital platform was built to integrate real-time data and predictive analytics for multiple hazards. The system provides a single, authoritative source for early warnings, supporting coordinated and proactive risk management.', ARRAY['Integrates data from multiple sources (weather, satellite, community).', 'Uses AI and predictive models to forecast hazard impacts.', 'Disseminates automated alerts via SMS, WhatsApp, and radio.', 'Generates accessible reports for stakeholders.', 'Embeds a multilingual chatbot for user support.']::text[], ARRAY['Multi-hazard integration (drought, floods, cyclones).', 'Real-time data and predictive analytics.', 'Interactive mapping and visualization dashboards.', 'Automated reporting and alerts.', 'Multilingual chatbot for non-technical users.', 'Community-level data reporting.']::text[], ARRAY['AI/ML', 'Generative AI', 'GIS', 'satellite imagery (ECMWF', 'CFS)', 'Python', 'web development', 'SMS', 'WhatsApp']::text[], 'Collaborated with UNDP Madagascar, the National Office for Risk and Disaster Management (BNGRC), the General Directorate of Meteorology (DGM), the Prevention and Emergency Management Unit (CPGU), and UN entities.', ARRAY['Madagascar']::text[], ARRAY[]::text[], NULL, 6),
('Socioeconomic Peace Index', 'socioeconomic-peace-index', ARRAY[]::text[], 'The Socioeconomic Peacebuilding Index (SEPI) is an interactive dashboard that measures and visualizes the structural socioeconomic conditions linked to conflict. It helps development actors, governments, and donors identify where integrated peacebuilding and development investments are most needed to foster sustained peace.', 'The Socioeconomic Peacebuilding Index (SEPI) is an interactive dashboard that measures and visualizes the structural socioeconomic conditions linked to conflict. It helps development actors, governments, and donors identify where integrated peacebuilding and development investments are most needed to foster sustained peace.', 'completed', 2025, 'GIS / Remote Sensing', 'GIS', ARRAY['Data integration', 'Dashboards', 'GIS', 'ML']::text[], ARRAY['UNDP COs']::text[], 'National-level data often hides the sub-national inequalities that drive conflict. Without a clear view of how socioeconomic deprivation and conflict are linked at a local level, it''s difficult to target peacebuilding and development investments effectively.', 'An interactive dashboard was developed to measure and map socioeconomic deprivation at the sub-national level. The index links deprivation to conflict data, enabling users to explore regional disparities and analyze the root causes of instability.', ARRAY['Measures socio-economic deprivation across five pillars: Education, Health, Food Security, Poverty, and Climate Resilience.', 'Aggregates indicators into a single composite score using a two-stage process.', 'Validates deprivation scores against observed conflict data from ACLED.', 'Visualizes regional disparities on an interactive digital dashboard.']::text[], ARRAY['Five-pillar framework for measuring deprivation.', 'Sub-national analysis at the Admin 1 level.', 'Two-stage aggregation logic (arithmetic and geometric mean).', 'Validation against empirical conflict data.', 'Interactive digital dashboard for data exploration.']::text[], ARRAY['R', 'Python', 'Power BI', 'GIS']::text[], 'Collaborated with the Armed Conflict Location and Event Data Project (ACLED) for conflict data.', ARRAY['Somalia', 'Kenya', 'South Sudan']::text[], ARRAY[]::text[], NULL, 7),
('Tech Volunteers for Resilience (Tech4R)', 'tech-volunteers-for-resilience-tech4r', ARRAY[]::text[], 'The Tech4R initiative mobilizes a global network of technology-skilled volunteers to co-create practical, inclusive, and open-source digital tools for disaster resilience, empowering local actors to respond swiftly and effectively to emergencies.', 'The Tech4R initiative mobilizes a global network of technology-skilled volunteers to co-create practical, inclusive, and open-source digital tools for disaster resilience, empowering local actors to respond swiftly and effectively to emergencies.', 'completed', 2023, 'Resilience', 'Open-source development', ARRAY['Digital volunteering', 'Open-source development', 'Low-Code/No-Code', 'Crowdsourcing']::text[], ARRAY['UN COs, Regional Offices, UN Entities, NGOs']::text[], 'Disasters are becoming more frequent and complex, creating critical digital gaps. Local communities and responders often lack the real-time data, inclusive technologies, and agile digital tools needed for effective disaster management.', 'A global network of trained tech volunteers is mobilized to rapidly co-develop open-source digital solutions with local partners. The initiative provides an immediate, coordinated, and innovative response to emergencies.', ARRAY['Partners submit digital challenges related to disaster resilience.', 'Tech4R analyzes requests and defines project requirements.', 'Online UN Volunteers are selected and trained.', 'Volunteers develop and deliver functional digital solution prototypes.', 'Ongoing support is provided to scale or customize solutions.']::text[], ARRAY['Rapid mobilization of a global tech volunteer network', '• Co-creation of open-source digital tools', '• Focus on Low-Code/No-Code solutions.', 'Crowdsourced data collection.', 'Includes the Frontier Technologies Radar for Disaster Risk Reduction (FTR4DRR).']::text[], ARRAY['Discord', 'Slack', 'WhatsApp', 'JIRA', 'GitHub', 'Microsoft Power BI', 'Power Automate', 'Kobo Toolbox', 'QGIS']::text[], 'The initiative is a partnership between UNDP ICPSD SDG AI Lab and UN Volunteers (UNV). It also involves collaboration with host entities, UN agencies, governmental agencies, NGOs, civil society organizations, and the private sector.', ARRAY['Global (Pilot in Turkiye)']::text[], ARRAY[]::text[], NULL, 8),
('Data Science Fellowship Programme', 'data-science-fellowship-programme', ARRAY[]::text[], 'This fellowship empowers early-career data scientists to lead inclusive digital transformation by providing practical experience on real-world projects. Fellows apply AI, machine learning, and geospatial technologies to sustainable development challenges, supported by mentoring and technical training.', 'This fellowship empowers early-career data scientists to lead inclusive digital transformation by providing practical experience on real-world projects. Fellows apply AI, machine learning, and geospatial technologies to sustainable development challenges, supported by mentoring and technical training.', 'active', 2022, 'Digital Skills Development', 'Training', ARRAY['AI', 'ML', 'NLP', 'GIS', 'Data Science training', 'Mentoring', 'Data Visualization', 'Blockchain']::text[], ARRAY['Internal UNDP']::text[], 'A digital and talent divide hinders developing countries from harnessing technologies like AI and data science for sustainable development. A lack of diversity in the tech field also risks perpetuating biases in digital solutions.', 'A fellowship programme was created to host cohorts of young data scientists, empowering them to become agents of change. The program provides advanced training, mentorship, and hands-on experience in developing digital solutions for the SDGs.', ARRAY['Mobilizes highly qualified young data scientists as on-site UN Youth and Specialist Volunteers.', 'Fellows lead and manage teams of online volunteers to augment project efforts.', 'Provides fellows with comprehensive training, mentorship, and coaching from leading tech companies.', 'Fellows develop and implement digital solutions to address development challenges like poverty and disaster response.']::text[], ARRAY['Development of digital solutions for SDGs.', 'Advanced training in AI, ML, GIS, and other frontier technologies.', 'Mentorship from leading tech companies.', 'Experience leading teams of online volunteers.', 'International work experience on development issues.', 'Focus on empowering women and youth from the Global South.']::text[], ARRAY['Python', 'R', 'Git', 'GitHub', 'TensorFlow', 'Scikit-Learn', 'Pandas', 'NLTK', 'ArcGIS', 'QGIS', 'Power BI', 'D3.js', 'AWS', 'Google Cloud', 'Azure DevOps', 'JIRA']::text[], 'The programme is a partnership between UNDP ICPSD SDG AI Lab and UN Volunteers. It also involves collaboration with private sector tech companies, academic institutions, and various UNDP Country and Regional Offices.', ARRAY['Global (Initial fellows from/in Turkiye', 'Serbia', 'France', 'USA', 'DRC', 'Ghana', 'Uganda', 'Russia', 'Brazil', 'China)']::text[], ARRAY[]::text[], NULL, 9),
('Digital Social Vulnerability Index (DSVI)', 'digital-social-vulnerability-index-dsvi', ARRAY[]::text[], 'The Digital Social Vulnerability Index (DSVI) is an innovative tool that uses machine learning and geographic information systems (GIS) to automate the analysis of social vulnerability, producing high-resolution maps that help governments and development partners identify at-risk populations.', 'The Digital Social Vulnerability Index (DSVI) is an innovative tool that uses machine learning and geographic information systems (GIS) to automate the analysis of social vulnerability, producing high-resolution maps that help governments and development partners identify at-risk populations.', 'completed', 2022, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'GIS', 'Data pipelines', 'Interactive mapping', 'Principal Component Analysis (PCA)']::text[], ARRAY['UNDP COs, Regional Office, Government, UN entities']::text[], 'Traditional social vulnerability assessments are often costly, time-consuming, and limited to coarse administrative boundaries. This results in a loss of granular detail, making it difficult to precisely target interventions for the most vulnerable communities.', 'An automated digital solution was developed to calculate social vulnerability using machine learning and geospatial data. This creates high-resolution, interactive maps that reveal vulnerability patterns beyond administrative borders, enabling more effective and targeted planning.', ARRAY['Gathers and processes geocoded household survey data (DHS, MICS).', 'Uses Principal Component Analysis (PCA) to identify and weight key vulnerability indicators.', 'Trains machine learning models on survey scores and geospatial data (e.g., nightlights, climate data).', 'Predicts and visualizes vulnerability on high-resolution maps.', 'Deploys results in an interactive online tool.']::text[], ARRAY['High-resolution vulnerability heatmaps.', 'Automated data science pipeline for SV score calculation.', 'Integration of household survey and geospatial data.', 'Interactive online platform for data exploration.', 'Customizable methodology for different contexts and hazards.']::text[], ARRAY['Python', 'Machine Learning (Scikit-Learn)', 'GIS (QGIS', 'ArcGIS)', 'Principal Component Analysis (PCA)', 'Geographically Weighted Regression (GWR)', 'Power BI']::text[], 'The DSVI is a collaborative effort involving the UNDP ICPSD SDG AI Lab, UNDP Disaster Risk Reduction and Recovery Team (DRT), and various UNDP Country Offices and Accelerator Labs (e.g., Côte d''Ivoire, Mali, Mauritania, Niger, Tajikistan).', ARRAY['Global (Piloted and implemented in Albania', 'Burkina Faso', 'Côte d''Ivoire', 'Ethiopia', 'Kenya', 'Lebanon', 'Mali', 'Mauritania', 'Niger', 'Somalia', 'Tajikistan)']::text[], ARRAY[]::text[], NULL, 10),
('Digital Solutions for SDGs (DS4SDGs) Course', 'digital-solutions-for-sdgs-ds4sdgs-course', ARRAY[]::text[], 'This course introduces learners to frontier technologies like AI, machine learning, and GIS, connecting them to real-world SDG challenges. Through practical case studies and project work, it equips development practitioners, students, and government officials with the skills to apply data science for social good.', 'This course introduces learners to frontier technologies like AI, machine learning, and GIS, connecting them to real-world SDG challenges. Through practical case studies and project work, it equips development practitioners, students, and government officials with the skills to apply data science for social good.', 'active', 2021, 'Digital Skills Development', 'Training', ARRAY['AI', 'ML', 'NLP', 'GIS', 'Curriculum design', 'E-learning/MOOC']::text[], ARRAY['UNDP COs, Universities']::text[], 'There is a significant gap between the potential of frontier technologies and their practical application to sustainable development challenges. Many practitioners and students lack the specific skills to leverage data science for the SDGs.', 'A practical, hands-on course was created that teaches participants how to use AI, Machine Learning, and GIS for sustainable development. The curriculum uses SDG-related datasets and case studies to build relevant, real-world skills.', ARRAY['Consists of 12 modules covering topics from Python to GIS and NLP.', 'Uses SDG-related datasets for practical exercises.', 'Engages learners through instructor-led training and webinars.', 'Concludes with a capstone project applying skills to a development problem.', 'A MOOC version with certification is in development.']::text[], ARRAY['12-module curriculum.', 'Focus on Python, ML, NLP, and GIS.', 'Real-world SDG case studies and datasets.', 'Open-source and community-driven content.', 'Capstone project for practical application.', 'MOOC with certification pathway.']::text[], ARRAY['Python', 'Twitter API', 'Tableau', 'AWS', 'Jupyter Notebooks']::text[], 'The course has been delivered in collaboration with academic institutions such as Koc University, Yildiz Technical University, and Istanbul University, as well as partners like the Samsung Innovation Campus and Frontier Tech Leaders.', ARRAY['(Delivered online and in partnership with universities in Turkiye)']::text[], ARRAY[]::text[], NULL, 11),
('Reef2Resilience – Coral Reef Health Assessment with Remote Sensing', 'reef2resilience-coral-reef-health-assessment-with-remote-sensing', ARRAY[]::text[], 'Uses satellite imagery and machine learning to map coral reef habitats and flag suspected bleaching, supporting the monitoring and protection of marine ecosystems.', 'Uses satellite imagery and machine learning to map coral reef habitats and flag suspected bleaching, supporting the monitoring and protection of marine ecosystems.', 'completed', 2019, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'Remote sensing', 'GIS', 'Satellite imagery']::text[], ARRAY['UNDP']::text[], 'Coral reefs are declining from warming and bleaching, but monitoring reef extent and bleaching across wide, remote areas is slow and costly using field surveys alone.', 'A remote-sensing workflow that classifies coral reef habitats from satellite imagery and detects suspected bleaching through change analysis, giving a repeatable way to monitor reef condition.', ARRAY['Collect Sentinel-2 satellite imagery for the reef area', 'Preprocess (atmospheric and sun-glint correction)', 'Classify habitats with ML and spectral indices', 'Detect suspected bleaching via change analysis between dates', 'Validate maps with expert review']::text[], ARRAY['Coral reef habitat mapping from satellite imagery', 'Suspected bleaching detection through change analysis', 'Bathymetry estimation for shallow reef areas', 'Automated, reusable Python / Google Earth Engine workflow', 'Built on free Sentinel-2 data and public reference maps']::text[], ARRAY['Sentinel-2 (MSI) imagery', 'SEN2COR', 'Google Earth Engine', 'Python', 'machine learning (Random Forest', 'K-means', 'Hartigan-Wong', 'decision/classification trees)', 'PCA', 'spectral indices (CTVI)', 'Allen Coral Atlas reference maps']::text[], 'Collabrated with UNDP', ARRAY[]::text[], ARRAY[]::text[], NULL, 12),
('Frontier Technology Radar for Disaster Risk Reduction (FTR4DRR)', 'frontier-technology-radar-for-disaster-risk-reduction-ftr4drr', ARRAY[]::text[], 'An online knowledge platform that tracks emerging technologies relevant to disaster management. It aims to increase stakeholders'' visibility of and access to newly-developed digital solutions to unleash their potential in Disaster Risk Reduction (DRR).', 'An online knowledge platform that tracks emerging technologies relevant to disaster management. It aims to increase stakeholders'' visibility of and access to newly-developed digital solutions to unleash their potential in Disaster Risk Reduction (DRR).', 'active', 2021, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'GIS', 'Web development', 'Tech mapping']::text[], ARRAY['UNDP HQ']::text[], 'Development stakeholders struggle to navigate the fast-growing tech industry and understand which digital solutions can most effectively support disaster risk management programs.', 'An online tool was developed to monitor and track existing and emerging digital solutions for anticipatory risk, risk reduction, and crisis recovery.', ARRAY['Tracks digital solutions for disaster management', 'Categorizes technologies by application, maturity, and crisis context', 'Visualizes use cases on an interactive radar and map']::text[], ARRAY['Interactive radar visualization', 'Maps technology maturity and disaster management phase', 'Filters by technology, disaster type, and country', 'Map view of project locations', 'Searchable use case database']::text[], ARRAY['Typescript', 'React', 'D3.js', 'sass']::text[], 'Collaborated with UNDP's Disaster Risk Reduction and Recovery for Building Resilience Team (DRT), the Connecting Business Initiative (CBi), and online UN Volunteers.', ARRAY['Global (knowledge platform)']::text[], ARRAY[]::text[], NULL, 13),
('OSDG', 'osdg', ARRAY[]::text[], 'OSDG provides open-source tools and datasets to classify and analyze text related to the Sustainable Development Goals. It helps researchers, governments, and other organizations align their work with the 2030 Agenda.', 'OSDG provides open-source tools and datasets to classify and analyze text related to the Sustainable Development Goals. It helps researchers, governments, and other organizations align their work with the 2030 Agenda.', 'active', 2021, 'Natural Language Processing', 'NLP', ARRAY['NLP', 'ML', 'Open-source datasets', 'API', 'volunteer mobilization and management']::text[], ARRAY['UNDP COs, Regional Offices, Government, UN entities, Universities']::text[], 'Organizations lack a standardized, transparent, and accessible way to classify documents and research according to the Sustainable Development Goals, leading to duplication of effort and difficulty in tracking contributions to the 2030 Agenda.', 'An open-source, multilingual tool and API were developed to automatically classify text and documents by their relevance to the SDGs, supported by a comprehensive, volunteer-created dataset and ontology.', ARRAY['User submits text or a PDF document.', 'Machine learning models perform initial SDG screening.', 'A keyword-based ontology verifies the preliminary labels.', 'Final SDG labels are assigned based on agreement between both methods.']::text[], ARRAY['Open-source text classification tool', 'Multilingual support for 19 languages', 'Free API for large-scale analysis', 'Publicly available, citizen-science dataset', 'PDF document upload and classification']::text[], ARRAY['Python', 'Machine Learning (BERT)', 'Prodigy (for labeling)', 'GitHub', 'Zenodo']::text[], 'Collaborated with PPMI, Dr. Nuria Bautista Puig and a global research network, and over 2,700 UN Online Volunteers from more than 130 countries.', ARRAY['Global (open-source tool and dataset)']::text[], ARRAY[]::text[], NULL, 14),
('Volunteer Data Scientists Initiative', 'volunteer-data-scientists-initiative', ARRAY[]::text[], 'This initiative mobilizes a global network of online data science volunteers to collaborate with UNDP teams on developing digital solutions for sustainable development, addressing challenges from poverty to disaster response.', 'This initiative mobilizes a global network of online data science volunteers to collaborate with UNDP teams on developing digital solutions for sustainable development, addressing challenges from poverty to disaster response.', 'active', 2019, '', 'Digital volunteering', ARRAY['Digital volunteering', 'Data science', 'AI/ML', 'GIS', 'NLP']::text[], ARRAY['UNDP COs, Regional Offices, Governments, UN entities']::text[], 'Development organizations often lack the specific technical talent required to leverage frontier technologies like AI and machine learning for solving complex sustainable development challenges.', 'A global network of online volunteers with expertise in data science is mobilized to collaborate on agile, task-based projects that create innovative digital solutions for the SDGs.', ARRAY['UNDP teams identify a development challenge.', 'SDG AI Lab recruits and coordinates skilled online volunteers.', 'Volunteers work in small teams on time-boxed sprints.', 'Teams deliver prototypes, reports, and code.']::text[], ARRAY['Access to a global talent pool of data scientists', 'Agile project management framework', 'Asynchronous, remote team collaboration', 'Networking and leadership opportunities for volunteers', 'Development of tailored digital solutions']::text[], ARRAY['Microsoft Teams', 'GitHub', 'Jira', 'Slack']::text[], 'Collaborated with United Nations Volunteers (UNV).', ARRAY['Global (Online volunteers from 45+ countries)']::text[], ARRAY[]::text[], NULL, 15),
('AI Value Chain Tool', 'ai-value-chain-tool', ARRAY[]::text[], 'An AI-powered knowledge management tool that enables UNDP teams and partners in Afghanistan to quickly search, summarize, and analyze internal policy and project documents related to agricultural value chains.', 'An AI-powered knowledge management tool that enables UNDP teams and partners in Afghanistan to quickly search, summarize, and analyze internal policy and project documents related to agricultural value chains.', 'completed', 2025, 'Natural Language Processing', 'NLP', ARRAY['NLP', 'GenAI', 'RAG', 'Chatbot']::text[], ARRAY['UNDP COs']::text[], 'Development teams working on Afghanistan''s agricultural sector lack a quick and efficient way to access and synthesize information from a fragmented collection of internal policy documents, hindering strategic planning and program design.', 'A digital knowledge tool was built to provide AI-powered search and summarization of internal reports. This enables users to get reliable, document-based insights for program planning, research, and evidence-based policymaking.', ARRAY['Collects and validates critical UNDP and partner documents', '• Ingests documents into a vector database.', 'Uses a RAG model with an LLM to answer queries', '• Users interact via a web interface for Q&A, summarization, and drafting.']::text[], ARRAY['Semantic search across documents', 'AI-powered document summarization', 'Q&A and chatbot interface', 'Assists in drafting proposals and concept notes', 'Power BI integration for dashboards']::text[], ARRAY['Power BI', 'Azure', 'Vector Database', 'Retrieval-Augmented Generation (RAG)', 'GPT models']::text[], NULL, ARRAY['Afghanistan']::text[], ARRAY[]::text[], NULL, 16),
('Innovation in Disaster Management: Leveraging Technology to Save More Lives Report', 'innovation-in-disaster-management-leveraging-technology-to-save-more-lives-report', ARRAY[]::text[], 'This study analyzes emerging technologies used in disaster preparedness and response, highlighting opportunities, limitations, and policy considerations to help guide humanitarian and development practitioners in strengthening resilience.', 'This study analyzes emerging technologies used in disaster preparedness and response, highlighting opportunities, limitations, and policy considerations to help guide humanitarian and development practitioners in strengthening resilience.', 'completed', 2024, '', 'Research', ARRAY['AI/ML research', 'Tech scouting', 'Disaster risk analytics']::text[], ARRAY['UNDP, UN Entities']::text[], 'Humanitarian and development practitioners need a better understanding of how to leverage emerging technologies and engage the private sector to improve disaster preparedness, response, and recovery.', 'A comprehensive report was produced to introduce key technologies, illustrate their use cases, and outline the main challenges and opportunities for their implementation in disaster management.', ARRAY['Researched 13 key frontier technologies.', 'Analyzed their application across the disaster management cycle', '• Mapped technologies to private sector networks.', 'Provided recommendations for practitioners.']::text[], ARRAY['Landscape analysis of 13 key technologies', 'Case studies on technology use in disasters', 'Assessment of implementation challenges and risks', 'Framework for private sector engagement', 'Recommendations for humanitarian practitioners']::text[], ARRAY['Not applicable (Research Report)']::text[], 'Collaborated with the United Nations Office for the Coordination of Humanitarian Affairs (OCHA) and the Connecting Business initiative (CBi).', ARRAY['Global (Report)']::text[], ARRAY[]::text[], NULL, 17),
('Illegal Dumpsite Detection', 'illegal-dumpsite-detection', ARRAY[]::text[], 'This project uses satellite imagery, machine learning, and geospatial analysis to detect and monitor illegal waste disposal sites, supporting environmental enforcement and cleanup prioritization by local authorities.', 'This project uses satellite imagery, machine learning, and geospatial analysis to detect and monitor illegal waste disposal sites, supporting environmental enforcement and cleanup prioritization by local authorities.', 'completed', 2023, 'GIS / Remote Sensing', 'GIS', ARRAY['Computer vision', 'Satellite imagery', 'ML', 'GIS']::text[], ARRAY['UNDP COs, Governments']::text[], 'Local authorities in countries like Guatemala, Peru, and Libya lack timely and cost-effective methods for detecting and monitoring the growing number of illegal dumpsites, which pose serious environmental and public health risks.', 'An AI-powered tool was developed to automatically analyze high-resolution satellite imagery and identify potential illegal dumpsites, enabling authorities to target interventions and streamline monitoring efforts.', ARRAY['Collect satellite imagery and ground-truth data from known dumpsites.', 'Pre-train a computer vision model on an open-source waste dataset.', 'Fine-tune the model using local data from the target country via transfer learning.', 'Deploy the model to identify and flag potential new dumpsites on a map.']::text[], ARRAY['Machine learning model for image classification', 'Uses publicly available satellite imagery', 'Differentiates between evident and non-evident dumpsites', 'Scalable to new geographical areas', 'Potential for a "human-in-the-loop" monitoring system']::text[], ARRAY['Python', 'Convolutional Neural Networks (CNN)', 'ResNet50', 'Feature Pyramid Network (FPN)', 'Google Maps Static API', 'GIS']::text[], 'Collaborated with UNDP Guatemala Accelerator Lab and the Ministry of Environment and Natural Resources (MARN) of Guatemala. The model was adapted from work by Politecnico di Milano. Planned collaborations include UNDP country offices in Peru and Libya.', ARRAY['Guatemala (completed)', 'Peru (planned)', 'Libya (planned)']::text[], ARRAY[]::text[], NULL, 18),
('SupTech for Fair Digital Finance – Morocco', 'suptech-for-fair-digital-finance-morocco', ARRAY[]::text[], 'This social listening platform analyzes social media discussions in Morocco to identify emerging risks, trends, and public concerns related to digital finance, providing authorities with timely insights for policy responses.', 'This social listening platform analyzes social media discussions in Morocco to identify emerging risks, trends, and public concerns related to digital finance, providing authorities with timely insights for policy responses.', 'completed', 2023, 'Natural Language Processing', 'NLP', ARRAY['NLP', 'ML', 'Knowledge graphs', 'Sentiment Analysis', 'Web Development']::text[], ARRAY['UNDP COs, Governments']::text[], 'Financial authorities need a way to understand consumer experiences and sentiments in real time, especially for vulnerable groups, but lack the tools to analyze vast amounts of social media data to inform consumer protection policies.', 'An AI-powered Supervisory Technology (SupTech) platform was developed to collect and analyze social media data in Arabic and French, offering insights on financial stability, inclusion, and market conduct to inform regulation.', ARRAY['Collects data from Twitter, Facebook, and Instagram.', 'Applies NLP for sentiment analysis, keyword extraction, and topic modeling in Arabic and French.', 'Uses a custom taxonomy co-designed with the Central Bank.', 'Visualizes insights and generates reports via a web application.']::text[], ARRAY['Real-time social media analysis in Arabic and French', 'Interactive visualizations and dashboards', 'Custom financial taxonomy for high accuracy', 'Sentiment, keyword, and topic trend analysis', 'PDF report generation', 'Online complaints page with speech-to-text']::text[], ARRAY['Python', 'Django']::text[], 'Collaborated with UNDP Morocco''s Accelerator Lab and the Central Bank of Morocco. Planned future collaboration includes the Qatar Computing Research Institute (QCRI) and Cambridge SupTech Lab.', ARRAY['Morocco']::text[], ARRAY[]::text[], NULL, 19),
('AI for Tourism', 'ai-for-tourism', ARRAY[]::text[], 'This web-based analytics platform analyzes tourism data from government agencies, tourism operators, and online platforms to generate real-time insights on visitor behavior, destinations, and economic opportunities through interactive dashboards.', 'This web-based analytics platform analyzes tourism data from government agencies, tourism operators, and online platforms to generate real-time insights on visitor behavior, destinations, and economic opportunities through interactive dashboards.', 'completed', 2023, 'Natural Language Processing', 'NLP', ARRAY['NLP', 'Data integration', 'Web development', 'Visualization', 'Data scrapping', 'Social Listening']::text[], ARRAY['UNDP COs, Governments']::text[], 'Governments and tourism operators in developing countries lack access to integrated, real-time data on visitor trends and preferences. This data gap hinders strategic planning, marketing, and investment, limiting the sector''s economic potential.', 'An AI-powered decision support system was developed to integrate and analyze data from multiple sources. It provides tourism authorities with actionable intelligence for planning, marketing, and investment decisions through interactive dashboards.', ARRAY['Scrapes data from online platforms (e.g., Booking.com, TripAdvisor)', '• Uses NLP and ML to perform sentiment and aspect-based analysis on reviews.', 'Integrates aviation data and other digital sources for demand signals', '• Presents findings via interactive dashboards, charts, and maps.']::text[], ARRAY['Automated data collection from major travel platforms', 'Aspect-based sentiment analysis', 'Interactive data visualizations and dashboards', 'Geographic analysis with interactive maps', 'Keyword extraction and trend analysis', 'Demographic and seasonal trend analysis']::text[], ARRAY['Django', 'React', 'Celery', 'Redis', 'PostgreSQL', 'Docker', 'Apify', 'Azure']::text[], 'Collaborated with the Ministry of Tourism in Malawi, Mzuzu University, and the Malawi Tourism Council. The initiative also involves partnerships with flydubai and UNDP Accelerator Labs.', ARRAY['Malawi', 'Tanzania (Zanzibar)']::text[], ARRAY[]::text[], NULL, 20),
('Coral Reef Mapping & Bleaching Monitoring', 'coral-reef-mapping-bleaching-monitoring', ARRAY[]::text[], 'This project uses machine learning and satellite imagery to develop a model that evaluates coral reef health and estimates the coastal protection services provided by healthy reef ecosystems.', 'This project uses machine learning and satellite imagery to develop a model that evaluates coral reef health and estimates the coastal protection services provided by healthy reef ecosystems.', 'completed', 2022, 'GIS / Remote Sensing', 'GIS', ARRAY['GIS', 'AI', 'Remote sensing', 'Machine Learning']::text[], ARRAY['N/A ???']::text[], 'Publicly available datasets for coral reefs are often outdated and have low resolution, making it difficult for stakeholders to monitor reef health and bleaching events effectively.', 'A classifier was built using satellite data to correctly classify coral reef habitats. This allows for the creation of updated habitat maps and the identification of coral bleaching events to enable faster in-situ response.', ARRAY['Process Sentinel-2 satellite data using atmospheric correction and deglinting.', 'Apply a classifier (e.g., Random Forest, SVM) to identify coral reef habitats.', 'Use the classification to create updated habitat and geomorphology maps.', 'Apply change detection algorithms to identify bleaching events.']::text[], ARRAY['Automated coral reef habitat classification', 'Bleaching event detection', 'Bathymetry estimation', 'Change detection mapping over time', 'Uses publicly available satellite data']::text[], ARRAY['Python', 'Sentinel-2', 'K-means', 'Random Forest', 'SVM', 'XGBoost']::text[], 'Collaborated with the United Nations Environment Programme – World Conservation Monitoring Centre (UNEP-WCMC) for data and research insights.', ARRAY['Global (Methodology Development)']::text[], ARRAY[]::text[], NULL, 21),
('INFF AI-powered Data Management and Analysis for SDG Finance', 'inff-ai-powered-data-management-and-analysis-for-sdg-finance', ARRAY[]::text[], 'Turns national financing-strategy documents into structured data and visualises financing trends for the INFF Facility, helping teams track reforms and compare progress across countries.', 'Turns national financing-strategy documents into structured data and visualises financing trends for the INFF Facility, helping teams track reforms and compare progress across countries.', 'completed', 2023, 'Natural Language Processing', 'NLP', ARRAY['NLP', 'Data structuring', 'Ontology/taxonomy', 'Data visualisation (Power BI)']::text[], ARRAY['UNDP']::text[], 'Integrated National Financing Frameworks generate a growing volume of policy documents and financing strategies. Keeping this information structured and comparable across countries is difficult with manual processes.', 'An Excel-based ontology and a Power BI prototype that organise INFF financing-strategy data into a consistent structure and visualise financing trends for analysis.', ARRAY['Define an ontology for financing-strategy data', 'Structure information from INFF documents against it', 'Consolidate into a central dataset', 'Visualise financing trends in a Power BI prototype']::text[], ARRAY['Structured ontology for INFF financing data', 'Standardised data pipeline', 'Power BI dashboard prototype for financing trends', 'Cross-country comparison of financing strategies']::text[], ARRAY['Excel-based ontology', 'Power BI', 'NLP', 'structured data pipelines']::text[], 'Developed with the INFF Facility.', ARRAY[]::text[], ARRAY[]::text[], NULL, 22),
('Earthquake Safety Routing', 'earthquake-safety-routing', ARRAY[]::text[], 'Uses satellite imagery and street data to find safer routes through a city after an earthquake, by mapping building risk and identifying streets that are less likely to be blocked by debris.', 'Uses satellite imagery and street data to find safer routes through a city after an earthquake, by mapping building risk and identifying streets that are less likely to be blocked by debris.', 'completed', 2022, 'GIS / Remote Sensing', 'GIS', ARRAY['AI/ML', 'Computer vision', 'GIS', 'Hazard modeling']::text[], ARRAY['Universities']::text[], 'Earthquakes can block streets with collapsed buildings and debris, making it hard to move safely through a city. Turkiye is among the countries most exposed to earthquake hazard.', 'A GIS and machine-learning workflow that maps building risk from satellite imagery, builds a risk heatmap over the street network, and identifies safer paths after an earthquake event.', ARRAY['Detect building footprints from satellite imagery', 'Map the street network from OpenStreetMap', 'Build a distance/risk heatmap around buildings and streets', 'Run a path-finding algorithm to identify safer routes']::text[], ARRAY['Building risk exposure mapping', 'Risk heatmap over the urban area', 'Street network graph for routing', 'Safer-path identification after an earthquake', 'Approach adaptable to multiple cities']::text[], ARRAY['Python', 'U-Net segmentation (computer vision)', 'PyTorch / TensorFlow / Keras', 'OpenStreetMap street graph', 'Dijkstra''s algorithm', 'SpaceNet building-footprint data', 'Google Maps Satellite / Mapbox imagery']::text[], 'Collaborated with Bilkent University (Industrial Engineering).', ARRAY['Turkiye (Istanbul – Fatih district)']::text[], ARRAY[]::text[], NULL, 23);


WITH matched AS (
  SELECT source.*, target.id
  FROM portfolio_import source
  JOIN LATERAL (
    SELECT id
    FROM projects
    WHERE slug = source.slug
      OR slug = ANY(source.match_slugs)
      OR lower(regexp_replace(title, '[^a-z0-9]+', '', 'g')) =
         lower(regexp_replace(source.title, '[^a-z0-9]+', '', 'g'))
    ORDER BY (slug = source.slug) DESC, updated_at DESC
    LIMIT 1
  ) target ON true
)
UPDATE projects target
SET
  title = source.title,
  summary = source.summary,
  description = source.description,
  project_status = source.project_status,
  project_year = source.project_year,
  impact_area = NULLIF(source.impact_area, ''),
  work_stream = NULLIF(source.work_stream, ''),
  capabilities_involved = source.capabilities_involved,
  best_fit = source.best_fit,
  problem = NULLIF(source.problem, ''),
  solution = NULLIF(source.solution, ''),
  how_it_works = source.how_it_works,
  features = source.features,
  tech_stack = source.tech_stack,
  collaboration_network = NULLIF(source.collaboration_network, ''),
  implementation_countries = source.implementation_countries,
  resource_links = source.resource_links,
  video_url = COALESCE(source.video_url, target.video_url),
  display_order = source.display_order,
  status = 'published',
  published_at = COALESCE(target.published_at, now()),
  updated_at = now()
FROM matched source
WHERE target.id = source.id;

INSERT INTO projects (
  title, slug, summary, description, project_status, project_year, impact_area,
  work_stream, capabilities_involved, best_fit, problem, solution, how_it_works,
  features, tech_stack, collaboration_network, implementation_countries,
  resource_links, video_url, display_order, status, published_at
)
SELECT
  source.title, source.slug, source.summary, source.description,
  source.project_status, source.project_year, NULLIF(source.impact_area, ''),
  NULLIF(source.work_stream, ''), source.capabilities_involved, source.best_fit,
  NULLIF(source.problem, ''), NULLIF(source.solution, ''), source.how_it_works,
  source.features, source.tech_stack, NULLIF(source.collaboration_network, ''),
  source.implementation_countries, source.resource_links, source.video_url,
  source.display_order, 'published', now()
FROM portfolio_import source
WHERE NOT EXISTS (
  SELECT 1
  FROM projects target
  WHERE target.slug = source.slug
     OR target.slug = ANY(source.match_slugs)
     OR lower(regexp_replace(target.title, '[^a-z0-9]+', '', 'g')) =
        lower(regexp_replace(source.title, '[^a-z0-9]+', '', 'g'))
);

SELECT
  COUNT(*) FILTER (WHERE status = 'published') AS published_projects,
  COUNT(*) FILTER (WHERE status = 'draft') AS draft_projects,
  COUNT(*) FILTER (WHERE status = 'archived') AS archived_projects
FROM projects;

COMMIT;


