-- Apply after 011_publications.sql. Records are inserted as drafts for the
-- editorial approval workflow; publish them from the CMS once approved.
INSERT INTO publications (title, slug, publication_type, authors, publication_date, date_label, publisher, summary, source_url, display_order, status)
VALUES
  ('Maturity Assessment of Drought Early Warning Systems in Southern Madagascar (2025)', 'maturity-assessment-of-drought-early-warning-systems-in-southern-madagascar-2025', 'report', NULL, '2025-12-11', NULL, 'UNDP ICPSD (SDG AI Lab–associated); partners: DGM, BNGRC, CPGU (Madagascar)', 'Evaluates the maturity of Madagascar''s drought early-warning system using the WMO multi-hazard EWS gap-analysis framework and elements of the UNDP–UNDRR Digital DRR Maturity Model; assesses digital maturity and data governance and recommends ways to strengthen anticipatory action. Published in English and French.', 'https://www.undp.org/policy-centre/istanbul/publications/maturity-assessment-drought-early-warning-systems-southern-madagascar-2025', 0, 'draft'),
  ('Digital Social Vulnerability Index 2023: Burkina Faso', 'digital-social-vulnerability-index-2023-burkina-faso', 'report', NULL, '2025-07-11', NULL, 'UNDP ICPSD SDG AI Lab & UNDP Burkina Faso Accelerator Lab', 'Summarizes DSVI study findings for Burkina Faso, using GIS, AI and machine learning to identify the most and least vulnerable communities, understand vulnerability drivers and validate results against other indicators. Part of the DSVI country series.', 'https://www.undp.org/policy-centre/istanbul/publications/digital-social-vulnerability-index-2023-burkina-faso', 1, 'draft'),
  ('Digital Social Vulnerability Index 2023: Niger', 'digital-social-vulnerability-index-2023-niger', 'report', NULL, '2025-07-11', NULL, 'UNDP ICPSD SDG AI Lab & UNDP Niger Accelerator Lab', 'Summarizes DSVI study findings for Niger, calculating nationwide high-resolution social vulnerability with GIS, AI and machine learning; outlines the main vulnerability challenges and the humanitarian context. Part of the DSVI country series.', 'https://www.undp.org/policy-centre/istanbul/publications/digital-social-vulnerability-index-2023-niger', 2, 'draft'),
  ('Illegal Dumpsite Detection Guatemala Findings Report', 'illegal-dumpsite-detection-guatemala-findings-report', 'report', NULL, '2025-03-07', NULL, 'UNDP ICPSD SDG AI Lab & UNDP Accelerator Lab Guatemala, in collaboration with Politecnico di Milano', 'Applies GIS, computer vision and machine learning to satellite imagery to identify illegal waste-dumping sites in Guatemala, enabling efficient, low-cost monitoring of solid-waste management aligned with national development priorities.', 'https://www.undp.org/policy-centre/istanbul/publications/illegal-dumpsite-detection-guatemala-findings-report', 3, 'draft'),
  ('Digital Social Vulnerability Index Technical Whitepaper', 'digital-social-vulnerability-index-technical-whitepaper', 'brief_white_paper', NULL, '2024-02-20', NULL, 'UNDP ICPSD SDG AI Lab, supported by the Disaster Risk Reduction and Recovery for Building Resilience Team (DRT)', 'Foundational technical manual for the DSVI methodology: explains its rationale, benefits and outcomes and describes calculating social vulnerability with GIS and machine learning to produce high-resolution maps and online tools. Anchors the DSVI country report series.', 'https://www.undp.org/publications/digital-social-vulnerability-index-technical-whitepaper', 4, 'draft'),
  ('Unraveling public perceptions of the Sustainable Development Goals for better policy implementation', 'unraveling-public-perceptions-of-the-sustainable-development-goals-for-better-policy-implementation', 'academic_paper', 'Núria Bautista-Puig, María Barreiro-Gen, Gustė Statulevičiūtė, Vilius Stančiauskas, Gökhan Dikmener, Dina Akylbekova, Rodrigo Lozano', NULL, 'February 20, 2024 (available online 6 December 2023)', 'Science of the Total Environment (Elsevier), Vol. 912, Art. 169114', 'Peer-reviewed journal article using the OSDG citizen-science initiative to analyze public perceptions of the SDGs and how citizen participation can strengthen SDG policy implementation. Co-authored by SDG AI Lab staff (Dikmener, Akylbekova) with OSDG partners.', 'https://www.sciencedirect.com/science/article/abs/pii/S0048969723077446', 5, 'draft'),
  ('Osdg Community Dataset: Unraveling the Societal Perceptions Around the Sustainable Development Goals', 'osdg-community-dataset-unraveling-the-societal-perceptions-around-the-sustainable-development-goals', 'academic_paper', 'Núria Bautista-Puig, Gustė Statulevičiūtė, Vilius Stančiauskas, Gökhan Dikmener, Dina Akylbekova', '2023-07-18', NULL, 'SSRN (working paper / preprint); DOI 10.2139/ssrn.4514364', 'Working paper presenting a case study of the OSDG Community Platform (2,000+ citizen-science participants); applies topic modelling and agreement scoring to 40,062 SDG-labelled text excerpts (v2023-01-01) to explore societal perceptions of the SDGs. Co-authored by SDG AI Lab staff (Dikmener, Akylbekova).', 'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4514364', 6, 'draft'),
  ('A RoBERTa Approach for Automated Processing of Sustainability Reports', 'a-roberta-approach-for-automated-processing-of-sustainability-reports', 'academic_paper', 'Merih Angin, Beyza Taşdemir, Cenk Arda Yılmaz, Gökcan Demiralp, Mert Atay, Pelin Angin, Gökhan Dikmener', '2022-12-02', NULL, 'Sustainability (MDPI), Vol. 14(23), Art. 16139', 'Peer-reviewed journal article benchmarking machine-learning / NLP models (notably fine-tuned RoBERTa) for classifying reports by SDG relevance, using the OSDG Community Dataset; supports automated processing of large collections of sustainability reports. Co-authored by SDG AI Lab (Dikmener).', 'https://www.mdpi.com/2071-1050/14/23/16139', 7, 'draft'),
  ('OSDG 2.0: a multilingual tool for classifying text data by UN Sustainable Development Goals (SDGs)', 'osdg-2-0-a-multilingual-tool-for-classifying-text-data-by-un-sustainable-development-goals-sdgs', 'academic_paper', 'Lukas Pukelis, Núria Bautista-Puig, Gustė Statulevičiūtė, Vilius Stančiauskas, Gokhan Dikmener, Dina Akylbekova', '2022-11-21', NULL, 'arXiv (arXiv:2211.11252); partnership of PPMI, UC3M & UNDP IICPSD SDG AI Lab', 'Preprint presenting OSDG 2.0, an improved iteration of the open-source SDG text-classification tool with expanded methodology and support for 15 languages. Co-authored by SDG AI Lab staff (Dikmener, Akylbekova).', 'https://arxiv.org/abs/2211.11252', 8, 'draft'),
  ('OSDG Community Dataset (OSDG-CD)', 'osdg-community-dataset-osdg-cd', 'dataset', 'OSDG; UNDP IICPSD SDG AI Lab; PPMI', NULL, 'First released 1 October 2021 (v2021.09); updated quarterly', 'Zenodo (DOI 10.5281/zenodo.5550238); OSDG, UNDP IICPSD SDG AI Lab & PPMI', 'Open, citizen-science dataset of tens of thousands of SDG-labelled text excerpts validated by 1,000+ (later 1,400+) OSDG Community Platform volunteers from 100+ countries. The first-version file holds 32,120 excerpts and 172,769 labels; used to train the OSDG tool and other ML/ontology SDG-classification work. CC BY 4.0.', 'https://doi.org/10.5281/zenodo.5550238', 9, 'draft')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  publication_type = EXCLUDED.publication_type,
  authors = EXCLUDED.authors,
  publication_date = EXCLUDED.publication_date,
  date_label = EXCLUDED.date_label,
  publisher = EXCLUDED.publisher,
  summary = EXCLUDED.summary,
  source_url = EXCLUDED.source_url,
  display_order = EXCLUDED.display_order;
